services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1

  test:
    build: ./app
    command: pytest
    volumes:
      - ./app:/app
